# Generated by Django 3.1 on 2020-08-28 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('confidence_percent', models.FloatField()),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='images.label')),
            ],
        ),
    ]
