# Generated by Django 3.1 on 2020-08-28 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200828_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='shape',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=4),
        ),
        migrations.AlterField(
            model_name='label',
            name='surface',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), blank=True, null=True, size=None),
        ),
    ]
